JobPortal/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobPortalDAL.Entity;
using Newtonsoft.Json;
using System.Web.Security;
using JobPortalDAL.Common;
using JobPortalDAL.DataAccess;
using System.Net.Http;
using JobPortalDAL.Manager;
using System.Configuration;

namespace JobPortal.Controllers
{    
    public class AccountController : Controller
    {
        private IAccount acc;
       // public string ApiUrl = ConfigurationManager.AppSettings["ApiUrl"].ToString();

        public AccountController()
        {
            acc = new AccountRepository();            
        }

        [AllowAnonymous]
        public ActionResult login(string returnUrl)
        {
            if (!User.Identity.IsAuthenticated)
            {
                Login lgin = new Login();
                if (Request.Cookies["UDetails"] != null)
                {
                    lgin.EmailId = Request.Cookies["UDetails"].Values["Email"];
                    lgin.Password = Request.Cookies["UDetails"].Values["Password"];
                    lgin.RememberMe = true;
                }
                return View(lgin);
            }
            else { return RedirectToAction("Index", "Home"); }                        
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<ActionResult> login(Login lgn, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(lgn);
            }

            var token = JsonConvert.DeserializeObject<Token>(acc.Login(lgn.EmailId, lgn.Password));
            token.userName = lgn.EmailId;

            if (token != null && token.access_token != "" && token.access_token != null)
            {                
                var result = JsonConvert.DeserializeObject<APIUserResponse>(await acc.GetUserDetailsAsync(token.access_token));                
                if (result.responseText[0] != null)
                {
                    FormsAuthentication.SetAuthCookie(lgn.EmailId, false);
                    var authTicket = new FormsAuthenticationTicket(1, lgn.EmailId, DateTime.Now, DateTime.Now.AddMinutes(20), lgn.RememberMe, result.responseText[0].Role);
                    string encryptedTicket = FormsAuthentication.Encrypt(authTicket);
                    var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket);
                    HttpContext.Response.Cookies.Add(authCookie);

                    var json = JsonConvert.SerializeObject(result.responseText[0]);
                    HttpCookie Ucookie = new HttpCookie("LoggedUDetails", json);
                    Ucookie.Expires.AddDays(15);
                    Response.Cookies.Add(Ucookie);

                    if (lgn.RememberMe)
                    {
                        HttpCookie cookie = new HttpCookie("UDetails");
                        cookie.Values.Add("Email", lgn.EmailId);
                        cookie.Values.Add("Password", lgn.Password);
                        cookie.Values.Add("Token", token.access_token);
                        cookie.Expires.AddDays(15);
                        Response.Cookies.Add(cookie);
                    }

                    if (Url.IsLocalUrl(returnUrl) && returnUrl.Length > 1 && returnUrl.StartsWith("/")
                        && !returnUrl.StartsWith("//") && !returnUrl.StartsWith("/\\"))
                    {
                        return Redirect(returnUrl);
                    }
                    else
                    {
                        return RedirectToAction("Index", "Home");
                    }
                }
            }
            else
            {
                ModelState.AddModelError("", "Invalid login attempt.");
                return View(lgn);
            }
            return View(lgn);            
        }

        [AllowAnonymous]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();            
            return RedirectToAction("login", "Account");
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult RegisterUser(User accnt)
        {
            var msg = "";
            accnt.Password = GenericClass.Hash(accnt.Password);
            var flag = false;// Umng.RegisterUser(accnt, out msg);
            if (flag == true)
            {
                var pp = "User registered successfully!";
                return Json(new { success = true, responseText = pp }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false, responseText = msg }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult ChangePassword(ChangePassword CPassword)
        {
            var msg = "";
            var flag = true; //Umng.ChangePassword(CPassword, Request.Cookies["MrLogin"].Values["Email"], out msg);
            if (flag == true)
            {
                var pp = "Password changed successfully!";
                return Json(new { success = true, responseText = pp }, JsonRequestBehavior.AllowGet);
            }
            else
            {                
                return Json(new { success = false, responseText = msg }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

JobPortal/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobPortal.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }
    }
}

JobPortal/Controllers/EmployerController.cs
using JobPortalDAL.Common;
using JobPortalDAL.DataAccess;
using JobPortalDAL.Entity;
using JobPortalDAL.Manager;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace JobPortal.Controllers
{
    public class EmployerController : Controller
    {
        private IJob Jb;
        public EmployerController()
        {
            Jb = new JobRepository();
        }
        // GET: Employer
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ActionResult AddJob()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddJob(Job jb)
        {
            var token = "";

            //jb.ExpireDate = DateTime.Now.AddDays(5).ToString();
            jb.CreatedDate = DateTime.Now.ToString();

            if (Request.Cookies["UDetails"] != null)
            {
                token = Request.Cookies["UDetails"].Values["Token"];
                var user = Request.Cookies["LoggedUDetails"].Value;

                var result = JsonConvert.DeserializeObject<User>(user);
                jb.UserID = result.UserID;
            }
            else
            {
                return RedirectToAction("login", "Account");
            }            

            if (token == null || token == "")
            {
                return RedirectToAction("login", "Account");
            }           

            var response = Jb.AddJob(jb, token);

            return Json(new { success = true, responseText = response }, JsonRequestBehavior.AllowGet);
        }
    }
}

JobPortal/Controllers/HomeController.cs
using JobPortalDAL.Manager;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobPortalDAL.DataAccess;
using System.Threading;
using System.Threading.Tasks;

namespace JobPortal.Controllers
{
    public class HomeController : Controller
    {
        private IJob jb;

        public HomeController()
        {
            jb = new JobRepository();
        }
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        // GET: Home
        public ActionResult JobList()
        {
            return View();
        }        

        public async Task<ActionResult> Jobs()
        {
            var allJobs = await jb.GetAllJobs();
            return Json(allJobs, JsonRequestBehavior.AllowGet);
        }

        public async Task<ActionResult> SeekerCount()
        {
            var Count = await jb.SeekerCount();
            return Json(Count, JsonRequestBehavior.AllowGet);
        }
    }
}

JobPortal/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace JobPortal.Controllers
{
    public class UserController : Controller
    {
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
    }
}

JobPortal/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>
<div class="col-lg-12 text-center">This is Admin </div>

JobPortal/Views/Employer/AddJob.cshtml
@{
    ViewBag.Title = "AddJob";
    Layout = "~/Views/Shared/_EmployerLayout.cshtml";
}
<link href="~/Scripts/SweetAlert/sweetalert.min.css" rel="stylesheet" />
<script src="~/Scripts/SweetAlert/sweetalert-dev.min.js"></script>
<form role="form" action="#">
    <div class="form-group">
        <label class="control-label">Job type</label>        
        <select class="form-control" id="jobType">
            <option value="1">Full time</option>
            <option value="2">Part time</option>
            <option value="1">Regular</option>
        </select>
    </div>
    <div class="form-group">
        <label class="control-label">Job description</label>
        <textarea id="jobDesc" class="form-control" rows="3" placeholder="Job description!!!"></textarea>
    </div>  
    <div class="form-group">
        <label class="control-label">Job Location</label>
        <input type="text" id="jobLoc" placeholder="Job Location" class="form-control" />
    </div>
    <div class="form-group">
        <label class="control-label">Min Experience Required</label>
        <input type="text" id="minExp" placeholder="Minimum experience required" class="form-control" />
    </div>
    <div class="form-group">
        <label class="control-label">Max Experience Required</label>
        <input type="text" id="maxExp" placeholder="Maximum experience required" class="form-control" />
    </div>
    <div class="form-group">
        <label class="control-label">ExpireDate</label>
        <input type="text" id="ExpDate" placeholder="dd/mm/yyyy" class="form-control" />
    </div>      
    <div class="margiv-top-10">
        <a href="javascript:;" onclick="AddJob()" class="btn green"> Add job </a>        
    </div>
</form>
<script>    

    function AddJob() {             
        var jobDesc = $("#jobDesc").val();
        var jobLoc = $("#jobLoc").val();
        var jobType = $("#jobType option:selected").val();
        var minExp = $("#minExp").val();
        var maxExp = $("#maxExp").val();
        var ExpDate = $("#ExpDate").val();
        var error = 0;
        if (jobDesc == null || jobDesc == "") {
            error++;
            $("#jobDesc").focus().addClass("error");
            return;
        }
        if (jobLoc == null || jobLoc == "") {
            error++;
            $("#jobLoc").focus().addClass("error");
            return;
        } else            
            if (minExp == null || minExp == "") {
                    error++;
                    $("#minExp").focus().addClass("error");
                    return;
                } else
                if (maxExp == null || maxExp == "") {
                        error++;
                        $("#maxExp").focus().addClass("error");
                        return;
                    } else                        
                            if (error == 0) {
                                $.ajax({
                                    type: 'POST',
                                    url: '@Url.Action("AddJob", "Employer")',
                                    data: { JobDescription: jobDesc, JobLocation: jobLoc, JobTypeID: jobType, MinExperienceRequired: minExp, MaxExperienceRequired: maxExp, ExpireDate: ExpDate },
                                    dataType: "text",
                                    success: function (data) {
                                        var response = $.parseJSON(data);
                                        if (response != null && response.success) {                                            
                                            swal('Congrats!', response.responseText, 'success');
                                            $("#jobDesc").val("");
                                            $("#jobLoc").val("");
                                            $("#minExp").val("");
                                            $("#maxExp").val("");
                                            $("#ExpDate").val("");
                                        } else {
                                            swal('Oops...', response.responseText, 'error');
                                            $("#jobDesc").val("");
                                            $("#jobLoc").val("");
                                            $("#minExp").val("");
                                            $("#maxExp").val("");
                                            $("#ExpDate").val("");
                                        }
                                    },
                                    error: function () {
                                        swal('Oops...', 'Something went wrong!', 'error');
                                    }
                                });
                            }
    }

</script>

JobPortal/Views/Employer/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_EmployerLayout.cshtml";
}

<h1>Test</h1>

JobPortal/Views/Home/JobList.cshtml
@{
    ViewBag.Title = "JobList";
    Layout = "~/Views/Shared/_HomeLayout.cshtml";
}

<!-- Jobs -->
<div class="total-ads main-grid-border">
    <div class="container">
       
        <div class="ads-grid">           
            <div class="ads-display col-md-12">
                <div class="wrapper">
                    <div class="bs-example bs-example-tabs" role="tabpanel" data-example-id="togglable-tabs">                        
                        <div id="myTabContent" class="tab-content">
                            <div role="tabpanel" class="tab-pane fade in active" id="home" aria-labelledby="home-tab">
                                <div>
                                    <div id="container">
                                        <div class="view-controls-list" id="viewcontrols">
                                            <label>view :</label>
                                            <a class="gridview"><i class="glyphicon glyphicon-th"></i></a>
                                            <a class="listview active"><i class="glyphicon glyphicon-th-list"></i></a>
                                        </div>
                                        <div class="clearfix"></div>
                                        <ul class="list" id="JbList">                                            
                                                      @*This area contains list of jobs*@              
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!-- // Jobs -->

<script type="text/javascript">
    $(document).ready(function () {               
        $.ajax({
            type: 'GET',
            url: '@Url.Action("Jobs", "Home")',
            async: true,
            success: function (data) {
                for (var i = 0; i < data.length; i++) {
                    $("#JbList").append('<li>' +
                        '<a href="#" onclick="JobDetails(' + data[i].ID + ')">' +
                        '<section class="list-left">' +
                        '<h5 class="title">' + data[i].JobDescription + '</h5>' +
                        '<p class="catpath">Created on ' + toDate(data[i].CreatedDate) + '</p>' +
                        '</section>' +
                        '<section class="list-right">' +
                        '<span class="date"><a class="btn btn-success" onclick="applyJob(' + data[i].ID + ')">apply</a></span>' +
                        '<span class="cityname">' + data[i].JobLocation + '</span>' +
                        '</section>' +
                        '<div class="clearfix"></div>' +
                        '</a >' +
                        '</li >');
                }
            },
            error: function (d) {                
                alert('Unable to get job list Please reload the page');
            }
        });

        var elem = $('#container ul');
        $('#viewcontrols a').on('click', function (e) {
            if ($(this).hasClass('gridview')) {
                elem.fadeOut(1000, function () {
                    $('#container ul').removeClass('list').addClass('grid');
                    $('#viewcontrols').removeClass('view-controls-list').addClass('view-controls-grid');
                    $('#viewcontrols .gridview').addClass('active');
                    $('#viewcontrols .listview').removeClass('active');
                    elem.fadeIn(1000);
                });
            }
            else if ($(this).hasClass('listview')) {
                elem.fadeOut(1000, function () {
                    $('#container ul').removeClass('grid').addClass('list');
                    $('#viewcontrols').removeClass('view-controls-grid').addClass('view-controls-list');
                    $('#viewcontrols .gridview').removeClass('active');
                    $('#viewcontrols .listview').addClass('active');
                    elem.fadeIn(1000);
                });
            }
        });
    });

    function applyJob(id) {
        alert(id);
    }
    function JobDetails(id) {
        alert(id);
    }

    function toDate(dateStr) {
        var date = new Date(dateStr);
        return (date.getMonth() + 1) + '/' + date.getDate() + '/' + date.getFullYear()
    }
</script>

JobPortal/Views/Shared/_HomeLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Webphonix job seekers | Home :: webphonix</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-select.css" rel="stylesheet" />
    <link href="~/Content/style.css" rel="stylesheet" type="text/css" media="all" />
    <link rel="stylesheet" href="~/Content/flexslider.css" type="text/css" media="screen" />
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    <!-- for-mobile-apps -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="All jobs on one click, Employer, Job seekers" />
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); }
    </script>
    <!-- //for-mobile-apps -->
    <!--fonts-->
    <link href='//fonts.googleapis.com/css?family=Ubuntu+Condensed' rel='stylesheet' type='text/css'>
    <link href='//fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,400italic,600,600italic,700,700italic,800,800italic' rel='stylesheet' type='text/css'>
    <!--//fonts-->
    <!-- js -->
    <script src="~/Scripts/jquery-1.11.3.min.js"></script>
    <!-- js -->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-select.js"></script>    
    <script type="text/javascript" src="~/Scripts/jquery.leanModal.min.js"></script>
    <link href="~/Content/jquery.uls.css" rel="stylesheet" />
    <link href="~/Content/jquery.uls.grid.css" rel="stylesheet" />
    <link href="~/Content/jquery.uls.lcd.css" rel="stylesheet" />
    <!-- Source -->
    <script src="~/Scripts/jquery.uls.data.js"></script>
    <script src="~/Scripts/jquery.uls.data.utils.js"></script>
    <script src="~/Scripts/jquery.uls.lcd.js"></script>
    <script src="~/Scripts/jquery.uls.languagefilter.js"></script>
    <script src="~/Scripts/jquery.uls.regionfilter.js"></script>
    <script src="~/Scripts/jquery.uls.core.js"></script>    
</head>
<body>
    <div class="header">
        <div class="container">
            <div class="logo">
                <a href='@Url.Action("Index","Home")'><span>Web</span>phonix</a>
            </div>
            
            <div class="header-right">
                @{
                    if (HttpContext.Current.User.Identity.IsAuthenticated)
                    {
                        if (HttpContext.Current.User.IsInRole("admin"))
                        {
                        <a class="account" href="@Url.Action("Index", "Admin")">My Account</a>
                        }
                        if (HttpContext.Current.User.IsInRole("seeker"))
                        {
                        <a class="account" href="@Url.Action("Index", "User")">My Account</a>
                        }
                        if (HttpContext.Current.User.IsInRole("employer"))
                        {
                        <a class="account" href="@Url.Action("Index", "Employer")">My Account</a>
                        }
                        <a class="account" href="@Url.Action("Logout", "Account")">Logout</a>
                    }
                    else
                    {
                        <a class="account" href="@Url.Action("login", "Account")">Welcome Guest Login</a>
                        }
                    }
            </div>

        </div>
    </div>
    
    <div class="@(ViewContext.RouteData.Values["action"].ToString() == "Index" ? "main-banner banner text-center" : "banner text-center")">
        <div class="container">
            <h1>Sell or Advertise   <span class="segment-heading">    anything online </span> with Resale</h1>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
            <div class="col-sm-3"></div>
            <div class="col-lg-6" style="@(ViewContext.RouteData.Values["action"].ToString() == "Index" ? "" : "display:none")">
                <input type="text" class="form-control" placeholder="Search your job here" />
            </div>
            <div class="col-sm-3"></div>
        </div>
    </div>
    @RenderBody()
    <!--footer section start-->
    <footer>
        <div class="footer-top">
            <div class="container">
                <div class="foo-grids">
                    <div class="col-md-3 footer-grid">
                        <h4 class="footer-head">Who We Are</h4>
                        <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
                        <p>The point of using Lorem Ipsum is that it has a more-or-less normal letters, as opposed to using 'Content here.</p>
                    </div>
                    <div class="col-md-3 footer-grid">
                        <h4 class="footer-head">Help</h4>
                        <ul>
                            <li><a href="howitworks.html">How it Works</a></li>
                            <li><a href="sitemap.html">Sitemap</a></li>
                            <li><a href="faq.html">Faq</a></li>
                            <li><a href="feedback.html">Feedback</a></li>
                            <li><a href="contact.html">Contact</a></li>
                            <li><a href="typography.html">Shortcodes</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 footer-grid">
                        <h4 class="footer-head">Information</h4>
                        <ul>
                            <li><a href="regions.html">Locations Map</a></li>
                            <li><a href="terms.html">Terms of Use</a></li>
                            <li><a href="popular-search.html">Popular searches</a></li>
                            <li><a href="privacy.html">Privacy Policy</a></li>
                        </ul>
                    </div>
                    <div class="col-md-3 footer-grid">
                        <h4 class="footer-head">Contact Us</h4>
                        <span class="hq">Our headquarters</span>
                        <address>
                            <ul class="location">
                                <li><span class="glyphicon glyphicon-map-marker"></span></li>
                                <li>CENTER FOR FINANCIAL ASSISTANCE TO DEPOSED NIGERIAN ROYALTY</li>
                                <div class="clearfix"></div>
                            </ul>
                            <ul class="location">
                                <li><span class="glyphicon glyphicon-earphone"></span></li>
                                <li>+0 561 111 235</li>
                                <div class="clearfix"></div>
                            </ul>
                            <ul class="location">
                                <li><span class="glyphicon glyphicon-envelope"></span></li>
                                <li><a href="mailto:info@example.com">mail@example.com</a></li>
                                <div class="clearfix"></div>
                            </ul>
                        </address>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
        <div class="footer-bottom text-center">
            <div class="container">
                <div class="footer-logo">
                    <a href="index.html"><span>Web</span>phonix</a>
                </div>
                <div class="footer-social-icons">
                    <ul>
                        <li><a class="facebook" href="#"><span>Facebook</span></a></li>
                        <li><a class="twitter" href="#"><span>Twitter</span></a></li>
                        <li><a class="flickr" href="#"><span>Flickr</span></a></li>
                        <li><a class="googleplus" href="#"><span>Google+</span></a></li>
                        <li><a class="dribbble" href="#"><span>Dribbble</span></a></li>
                    </ul>
                </div>
                <div class="copyrights">
                    <p> © @DateTime.Now.Year Webphonix. All Rights Reserved | Design by  <a href="http://webphonix.com/"> Webphonix</a></p>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </footer>
    <!--footer section end-->
</body>
</html>